### ISSUE TITLE
COMMUNITY SERVER LIST NOT WORKING

### ISSUE THREAD

**Issue by Jerrychenshen** [nitrog0d/palworld-arm64#2]
Hi there,

Works fine for me but still have a few questions.

1. "COMMUNITY_SERVER=True" seems not working, not sure of other var works.
2.  Does "ALWAYS_UPDATE_ON_START=true" update the server from the official image every time I bring the container up?
3. Noob question for new docker users like me, if your images have been updated, how do I update my container to keep the date to your images without recreating one. How do I keep my saves safe?

Thanks in advance and thanks for your work.

**Comment by nitrog0d** [comment]
1. Community server list is really really big, I think if you wanted to find your server you would have to scroll multiple pages, I know it works because I was testing and had randomly people joining my server.
2. Correct, every time you bring the container up, SteamCMD will try to update the files for the server.
3. Your files are usually safe as you mount them as a "volume", images don't affect them (unless they delete the files manually, which I don't), you might want to add a backup script to backup to your local host if you're worried, I'll add one soon, as for updating the image, you can take the container down and up again I think? Just Google on how to update the image of a container with docker compose, I'm not sure myself

**Comment by vladbogun1** [comment]
same for me, i even try to filter out all servers by name, but i cant find my server
![image](https://github.com/nitrog0d/palworld-arm64/assets/34967580/54fbae10-7f14-4594-ac90-e5326f1c72f1)

i can see it in "Last connected servers" 
![image](https://github.com/nitrog0d/palworld-arm64/assets/34967580/9fbd845c-6752-44a3-8278-674ba979ee30)

but not in community servers tab
![image](https://github.com/nitrog0d/palworld-arm64/assets/34967580/9ad40206-2e3e-4797-a3f9-c17ab6ca49fb)

**Comment by lbbboy** [comment]
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
.
me to
